fail_fast: true

repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.20.1
    hooks:
      - id: typos
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        language: system
        types: [file, rust]
        entry: cargo fmt -- --check
        pass_filenames: false

      - id: clippy
        name: clippy
        language: system
        types: [file, rust]
        entry: cargo clippy --all -- -D warnings # Use -D warnings option to ensure the job fails when encountering warnings
        pass_filenames: false

      - id: tests
        name: tests
        language: system
        types: [file, rust]
        entry: cargo test
        pass_filenames: false