[workspace]
resolver = "2"
members = [
    "crates/chef",
    "crates/farm",
    "crates/kitchen",
    "crates/lemon_filling",
    "crates/lemon_meringue_pie",
    "crates/meringue",
    "crates/pastry",
]

# Shared dependencies that all of the crates need - for now this is just the 
# `radixdlt-scrypto` dependencies
[workspace.dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs/", rev = "6f33088e8100a2ea9586c8c3ecf98ab51d5aba62" }

[profile.release]
incremental = false
panic = 'unwind'
codegen-units = 1
