[workspace]
resolver = "2"
members = [
    "crates/chef",
    "crates/farm",
    "crates/kitchen",
    "crates/lemon_filling",
    "crates/lemon_meringue_pie",
    "crates/meringue",
    "crates/pastry",
]

[workspace.dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs/", rev = "aa338ccb435d81d36f7adef8954bcffebdd4a7d1" }

[profile.release]
incremental = false
panic = 'unwind'
codegen-units = 1
